// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDME6NKRwvgSbfSvnTKP0gHPryC4v_aO5M',
    appId: '1:1081896712217:web:6be09676d5f9550a961288',
    messagingSenderId: '1081896712217',
    projectId: 'eofficeapp-d354b',
    authDomain: 'eofficeapp-d354b.firebaseapp.com',
    storageBucket: 'eofficeapp-d354b.appspot.com',
    measurementId: 'G-6X2FJY8H6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0V3CRleTN8n4P8cDs8i4jFD3r7S9Fik',
    appId: '1:1081896712217:android:d81b3294c083b5dc961288',
    messagingSenderId: '1081896712217',
    projectId: 'eofficeapp-d354b',
    storageBucket: 'eofficeapp-d354b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYIhvUtB3cseish4fIwXcOWcapP5CNyu4',
    appId: '1:1081896712217:ios:8d1c693b7618fe07961288',
    messagingSenderId: '1081896712217',
    projectId: 'eofficeapp-d354b',
    storageBucket: 'eofficeapp-d354b.appspot.com',
    iosBundleId: 'com.example.eOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYIhvUtB3cseish4fIwXcOWcapP5CNyu4',
    appId: '1:1081896712217:ios:8d1c693b7618fe07961288',
    messagingSenderId: '1081896712217',
    projectId: 'eofficeapp-d354b',
    storageBucket: 'eofficeapp-d354b.appspot.com',
    iosBundleId: 'com.example.eOffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDME6NKRwvgSbfSvnTKP0gHPryC4v_aO5M',
    appId: '1:1081896712217:web:12e8139eeafce5f6961288',
    messagingSenderId: '1081896712217',
    projectId: 'eofficeapp-d354b',
    authDomain: 'eofficeapp-d354b.firebaseapp.com',
    storageBucket: 'eofficeapp-d354b.appspot.com',
    measurementId: 'G-N1YPRZEHDJ',
  );

}
